import { createApp } from "vue";
import { createPinia } from "pinia";
import "ant-design-vue/dist/antd.css";
import App from "./App.vue";
import router from "./router";
import loadAntd from "./antd";
const app = createApp(App);
app.use(createPinia());
app.use(router);
loadAntd(app);
app.mount("#app");
